# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu18_04_64"

   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true

     # Customize the amount of memory on the VM:
     vb.memory = "2048"
   end

   config.vm.provision "shell", inline: <<-SHELL
     sudo apt-add-repository -y ppa:rquillo/ansible
     sudo apt-get update
     sudo apt-get -y install ansible
     cd /home/vagrant
     mkdir provision
     mkdir provision/tasks
     chown -R vagrant.vagrant provision
     cd provision
     cp /vagrant/localhost .
     cp /vagrant/site.yml .
     cp /vagrant/provision.sh .
     chown vagrant.vagrant localhost
     chown vagrant.vagrant site.yml
     chown vagrant.vagrant provision.sh
     chmod -x localhost
     chmod -x site.yml
     chmod +x provision.sh
     cd tasks
     cp /vagrant/tasks/*.yml .
     chmod -x *.yml
   SHELL
end
