---
# tasks/japanese.yml


  - name: Apt install language-pack-ja language-pack-ja-base
    apt: pkg={{ item }} force=yes update_cache=yes
    with_items:
      - language-pack-ja-base
      - language-pack-ja

  - name: "Locale UPDATE"
    command: update-locale LANG=ja_JP.UTF-8 LANGUAGE="ja_JP:ja"

  - name: "Japanese Environment Setup"
    shell: "{{ item }}"
    with_items:
      - wget -q https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg -O- | sudo apt-key add -
      - wget -q https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg -O- | sudo apt-key add -
      - sudo wget https://www.ubuntulinux.jp/sources.list.d/trusty.list -O /etc/apt/sources.list.d/ubuntu-ja.list

  - name: "update cache"
    apt: update_cache=yes

  - name: "apt apgrade"
    apt: upgrade=yes
     
  - name: "japanese software install"
    apt: name=ubuntu-defaults-ja
