---
# tasks/ubuntu_desktop.yml

  - name: "add-apt-repository ppa:gnome3-team/gnome3"
    apt_repository: repo='ppa:gnome3-team/gnome3'

  - name: Apt install ubuntu desktop
    apt: pkg={{ item }} force=yes update_cache=yes
    with_items:
      - xfce4
      - gnome-shell
      - ubuntu-desktop
      - gdm
