---
- hosts: 127.0.0.1
  user: vagrant
  sudo: yes
  tasks:
    - name: "apt-get install xfce4"
      apt: name=xfce4
    - name: "add-apt-repository ppa:gnome3-team/gnome3"
      apt_repository: repo='ppa:gnome3-team/gnome3'
    - name: "apt-get install gnome-shell"
      apt: name=gnome-shell
    - name: "apt-get install ubuntu-desktop"
      apt: name=ubuntu-desktop
    - name: "apt-get install gdm"
      apt: name=gdm
    - name: "apt-get install language-pack-ja-base"
      apt: name=language-pack-ja-base
    - name: "apt-get install language-pack-ja"
      apt: name=language-pack-ja
    - name: "Locale UPDATE"
      command: update-locale LANG=ja_JP.UTF-8 LANGUAGE="ja_JP:ja"

