---
- hosts: 127.0.0.1
  user: vagrant
  sudo: yes
  tasks:
    - name: "apt-get install xfce4"
      apt: name=xfce4
    - name: "add-apt-repository ppa:gnome3-team/gnome3"
      apt_repository: repo='ppa:gnome3-team/gnome3'
    - name: "apt-get install gnome-shell"
      apt: name=gnome-shell
    - name: "apt-get install ubuntu-desktop"
      apt: name=ubuntu-desktop
    - name: "apt-get install gdm"
      apt: name=gdm
    - name: "apt-get install language-pack-ja-base"
      apt: name=language-pack-ja-base
    - name: "apt-get install language-pack-ja"
      apt: name=language-pack-ja
    - name: "Locale UPDATE"
      command: update-locale LANG=ja_JP.UTF-8 LANGUAGE="ja_JP:ja"
    - name: "Japanese Environment Setup#1"
      shell: wget -q https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg -O- | sudo apt-key add -
    - name: "Japanese Environment Setup#2"
      shell: wget -q https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg -O- | sudo apt-key add -
    - name: "Japanese Environment Setup#3"
      shell: sudo wget https://www.ubuntulinux.jp/sources.list.d/precise.list -O /etc/apt/sources.list.d/ubuntu-ja.list
    - name: "Japanese Environment Setup#4"
      apt: update_cache=yes
    - name: "Japanese Environment Setup#5"
      apt: upgrade=yes
    - name: "Japanese Environment Setup#6"
      apt: name=ubuntu-defaults-ja
