# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu64"

   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true

     # Customize the amount of memory on the VM:
     vb.memory = "2048"
   end

   config.vm.provision "shell", inline: <<-SHELL
     sudo apt-add-repository -y ppa:rquillo/ansible
     sudo apt-get update
     sudo apt-get -y install ansible
     cd ~
     mkdir ansible
     cd ansible
     cp /vagrant/localhost .
     cp /vagrant/site.yml .
     chmod -x localhost
     chmod -x site.yml
   SHELL
end
